// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241003065956_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EngPhrase")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RusPhrase")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Exercises", "lessons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6ed88863-0c5d-45cd-b361-3071bf62a907"),
                            EngPhrase = "Ты не увидишь.",
                            RusPhrase = "You will not see."
                        },
                        new
                        {
                            Id = new Guid("ec6ea7e1-3dbb-45a7-801c-3441c6ef962f"),
                            EngPhrase = "Will we show?",
                            RusPhrase = "Мы покажем?"
                        },
                        new
                        {
                            Id = new Guid("dacb0b73-7bb2-491f-9bf6-adb1f3e2f50f"),
                            EngPhrase = "She worked.",
                            RusPhrase = "Она работала."
                        },
                        new
                        {
                            Id = new Guid("f8d8fcb2-4df3-4321-9538-fe576ef04c2d"),
                            EngPhrase = "You didn't think.",
                            RusPhrase = "Ты не думал."
                        },
                        new
                        {
                            Id = new Guid("69dfc0ba-ac95-44bb-b412-b36b2a45f6bb"),
                            EngPhrase = "Will i look?",
                            RusPhrase = "Я посмотрю?"
                        });
                });

            modelBuilder.Entity("Domain.Lessons.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Number")
                        .HasMaxLength(255)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Lessons", "lessons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("099df6d4-f116-4b6e-8cae-96dd9f3623dd"),
                            Name = "Базовая форма глагола",
                            Number = 1
                        });
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "identity");
                });

            modelBuilder.Entity("Domain.Exercises.Exercise", b =>
                {
                    b.OwnsMany("Domain.Exercises.Entities.Word", "Words", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ExerciseId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Number")
                                .HasColumnType("integer");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("ExerciseId");

                            b1.ToTable("Words", "lessons");

                            b1.WithOwner()
                                .HasForeignKey("ExerciseId");

                            b1.HasData(
                                new
                                {
                                    Id = new Guid("5a31e7cc-939b-4ee8-afcf-d99662d80a4c"),
                                    ExerciseId = new Guid("6ed88863-0c5d-45cd-b361-3071bf62a907"),
                                    Number = 1,
                                    Type = 14
                                },
                                new
                                {
                                    Id = new Guid("37312666-31bc-4ba6-819b-cfeeebddd54c"),
                                    ExerciseId = new Guid("6ed88863-0c5d-45cd-b361-3071bf62a907"),
                                    Number = 2,
                                    Type = 9
                                },
                                new
                                {
                                    Id = new Guid("9f902885-4e65-4b7d-a72b-7dab937a8498"),
                                    ExerciseId = new Guid("6ed88863-0c5d-45cd-b361-3071bf62a907"),
                                    Number = 3,
                                    Type = 16
                                },
                                new
                                {
                                    Id = new Guid("b1218895-1d15-4bb5-9da6-0f5aa9766724"),
                                    ExerciseId = new Guid("ec6ea7e1-3dbb-45a7-801c-3441c6ef962f"),
                                    Number = 1,
                                    Type = 9
                                },
                                new
                                {
                                    Id = new Guid("5ade30d1-77bb-43f6-bd92-82aec6aa3222"),
                                    ExerciseId = new Guid("ec6ea7e1-3dbb-45a7-801c-3441c6ef962f"),
                                    Number = 2,
                                    Type = 14
                                },
                                new
                                {
                                    Id = new Guid("d2d2dabb-4033-4fee-abec-8eab0c408c84"),
                                    ExerciseId = new Guid("ec6ea7e1-3dbb-45a7-801c-3441c6ef962f"),
                                    Number = 3,
                                    Type = 16
                                },
                                new
                                {
                                    Id = new Guid("6781979f-ea8a-44a9-be13-93944ff40345"),
                                    ExerciseId = new Guid("dacb0b73-7bb2-491f-9bf6-adb1f3e2f50f"),
                                    Number = 1,
                                    Type = 14
                                },
                                new
                                {
                                    Id = new Guid("248c01ec-7b14-4f91-a9ed-9390bd0f13d4"),
                                    ExerciseId = new Guid("dacb0b73-7bb2-491f-9bf6-adb1f3e2f50f"),
                                    Number = 2,
                                    Type = 16
                                },
                                new
                                {
                                    Id = new Guid("900133cd-7e00-4ce5-b2d8-87ba098ccf6c"),
                                    ExerciseId = new Guid("f8d8fcb2-4df3-4321-9538-fe576ef04c2d"),
                                    Number = 1,
                                    Type = 14
                                },
                                new
                                {
                                    Id = new Guid("1b4bcdc8-e2a3-4d19-9881-082cb4498fbd"),
                                    ExerciseId = new Guid("f8d8fcb2-4df3-4321-9538-fe576ef04c2d"),
                                    Number = 2,
                                    Type = 13
                                },
                                new
                                {
                                    Id = new Guid("2aab0806-f1b2-4b07-b6cb-e8c9990cf577"),
                                    ExerciseId = new Guid("f8d8fcb2-4df3-4321-9538-fe576ef04c2d"),
                                    Number = 3,
                                    Type = 16
                                },
                                new
                                {
                                    Id = new Guid("0b73df81-66af-4114-ad46-2de5277e873d"),
                                    ExerciseId = new Guid("69dfc0ba-ac95-44bb-b412-b36b2a45f6bb"),
                                    Number = 1,
                                    Type = 9
                                },
                                new
                                {
                                    Id = new Guid("048a3fde-45da-4846-b695-46a84a6a0ab7"),
                                    ExerciseId = new Guid("69dfc0ba-ac95-44bb-b412-b36b2a45f6bb"),
                                    Number = 2,
                                    Type = 14
                                },
                                new
                                {
                                    Id = new Guid("460e1c54-fb25-4d6e-b937-864515821542"),
                                    ExerciseId = new Guid("69dfc0ba-ac95-44bb-b412-b36b2a45f6bb"),
                                    Number = 3,
                                    Type = 16
                                });
                        });

                    b.Navigation("Words");
                });

            modelBuilder.Entity("Domain.Lessons.Lesson", b =>
                {
                    b.OwnsMany("Domain.Exercises.ValueObjects.ExerciseId", "ExerciseIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("LessonId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("ExerciseId");

                            b1.HasKey("Id");

                            b1.HasIndex("LessonId");

                            b1.ToTable("LessonExerciseIds", "lessons");

                            b1.WithOwner()
                                .HasForeignKey("LessonId");

                            b1.HasData(
                                new
                                {
                                    Id = 1,
                                    LessonId = new Guid("099df6d4-f116-4b6e-8cae-96dd9f3623dd"),
                                    Value = new Guid("6ed88863-0c5d-45cd-b361-3071bf62a907")
                                },
                                new
                                {
                                    Id = 2,
                                    LessonId = new Guid("099df6d4-f116-4b6e-8cae-96dd9f3623dd"),
                                    Value = new Guid("ec6ea7e1-3dbb-45a7-801c-3441c6ef962f")
                                },
                                new
                                {
                                    Id = 3,
                                    LessonId = new Guid("099df6d4-f116-4b6e-8cae-96dd9f3623dd"),
                                    Value = new Guid("dacb0b73-7bb2-491f-9bf6-adb1f3e2f50f")
                                },
                                new
                                {
                                    Id = 4,
                                    LessonId = new Guid("099df6d4-f116-4b6e-8cae-96dd9f3623dd"),
                                    Value = new Guid("f8d8fcb2-4df3-4321-9538-fe576ef04c2d")
                                },
                                new
                                {
                                    Id = 5,
                                    LessonId = new Guid("099df6d4-f116-4b6e-8cae-96dd9f3623dd"),
                                    Value = new Guid("69dfc0ba-ac95-44bb-b412-b36b2a45f6bb")
                                });
                        });

                    b.OwnsMany("Domain.Scores.ValueObjects.ScoreId", "ScoreIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("LessonId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("ScoreId");

                            b1.HasKey("Id");

                            b1.HasIndex("LessonId");

                            b1.ToTable("LessonScoreIds", "lessons");

                            b1.WithOwner()
                                .HasForeignKey("LessonId");
                        });

                    b.Navigation("ExerciseIds");

                    b.Navigation("ScoreIds");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.OwnsMany("Domain.Scores.ValueObjects.ScoreId", "ScoreIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("ScoreId");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserScoreIds", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("ScoreIds");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
